"""Import PDF-reviewed robot-arm priority material data sheets."""
from __future__ import annotations
import argparse,csv,hashlib,json
from pathlib import Path
F=("material_id","property","value","unit","temperature_K","uncertainty","data_kind","condition","source_id","source_locator","notes","raw_source_file","raw_sheet","raw_row_number","raw_row_json")
def main():
 p=argparse.ArgumentParser();p.add_argument('--source-dir',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args()
 names=['Markforged_17-4PH.pdf','Kemper_KHP181_CuCrZr.pdf','Rodacciai_42CrMo4.pdf','MakerBot_Nylon12CF.pdf','UltiMaker_PPSCF.pdf','Kormax_C11000.pdf','CF_PEKK.pdf','Hexcel_IM7_8552.pdf','Instavoxel_7075_T6.pdf','AON3D_PEKK_A.pdf','Gabrian_2024_T3.pdf','Ovako_20MnCr5.pdf','ExclusiveMagnesium_AZ91.pdf']
 if a.output.exists() or any(not(a.source_dir/x).is_file() for x in names): raise SystemExit('source files missing or output exists')
 ms=[]; pts=[]; als=[]
 def add(mid,name,family,grade,state,src,file,values):
  ms.append({'material_id':mid,'display_name':name,'family':family,'grade':grade,'UNS/standard':'','product_state':state,'source_id':src,'data_role':'manufacturer/source-backed material evidence','temperature_coverage':'room temperature; see evidence conditions','composition_available':'source datasheet','process_metadata':state,'notes':'D estimates, where present, remain separate and cannot affect screening.','raw_source_file':file,'raw_sheet':'','raw_row_number':'1','raw_row_json':'PDF-reviewed 2026-08-25'})
  alias_values = [grade, name]
  if '42CrMo4' in grade: alias_values.extend(['42CrMo4', '4140'])
  if grade == 'PPS-CF': alias_values.extend(['PPS CF', 'PPSCF'])
  if grade == 'C11000': alias_values.extend(['C110', 'C1100'])
  if grade == 'CF-PEKK': alias_values.extend(['CF/PEKK', 'AS4/PEKK'])
  als.extend({'material_id':mid,'alias':x,'alias_type':'grade','source':src} for x in dict.fromkeys(alias_values))
  for prop,val,unit,cond,page in values:
   locator = str(page) if str(page).startswith('http') else f'PDF page {page}'
   pts.append({'material_id':mid,'property':prop,'value':str(val),'unit':unit,'temperature_K':'296.15','uncertainty':'','data_kind':'manufacturer_typical_or_minimum','condition':cond,'source_id':src,'source_locator':locator,'notes':'PDF-reviewed source value; state retained.' if file else 'Manufacturer official web-page value; access date retained in source_id/locator.','raw_source_file':file,'raw_sheet':'','raw_row_number':str(page),'raw_row_json':json.dumps({'property':prop,'value':val,'unit':unit})})
 add('MAT-ROBOT-SEED-17-4PH-H900','Markforged 17-4PH H900','金属增材沉淀硬化不锈钢','17-4PH H900','Metal X printed; H900 heat treatment','SRC-MARKFORGED-17-4PH-REV2.1',names[0],[('ultimate_tensile_strength',1250,'MPa','Metal X H900; ASTM E8',1),('yield_strength',1100,'MPa','Metal X H900; ASTM E8',1),('elongation',6,'%', 'Metal X H900; ASTM E8',1),('youngs_modulus',170,'GPa','Metal X H900; ASTM E8',1),('hardness',36,'HRC','Metal X H900; ASTM E18',1)])
 add('MAT-ROBOT-SEED-CUCRZR','Kemper KHP 181（CuCrZr）','导电/热管理铜铬锆合金','CuCrZr','soft temper; room temperature','SRC-KEMPER-KHP181-REV2026',names[1],[('density',8.9,'g/cm³','soft temper; room temperature',1),('youngs_modulus',137,'GPa','soft temper; room temperature',1),('thermal_conductivity',335,'W/(m·K)','soft temper; room temperature',1),('thermal_expansion_coefficient',17.3,'ppm/K','soft temper; room temperature',1),('ultimate_tensile_strength',480,'MPa','R480 temper; minimum range endpoint',1),('yield_strength',450,'MPa','R480 temper; minimum',1),('elongation',8,'%', 'R480 temper; minimum',1),('hardness_vickers',150,'HV','R480 temper; range lower endpoint',1)])
 add('MAT-ROBOT-SEED-42CRMO-QT','42CrMo4 调质钢','合金结构钢','42CrMo4 / 4140','hot-rolled; quenched and tempered; 16–40 mm','SRC-RODACCIAI-42CRMO4-REV2018',names[2],[('yield_strength',750,'MPa','+QT; 16–40 mm; minimum',1),('ultimate_tensile_strength',1000,'MPa','+QT; 16–40 mm; range lower endpoint',1),('elongation',11,'%', '+QT; 16–40 mm; minimum',1)])
 add('MAT-ROBOT-SEED-PA12-CF-FDM','MakerBot Nylon 12 Carbon Fiber','FDM 短切碳纤维增强 PA12','PA12-CF','METHOD/METHOD X; Composite Extruder 1C; print parameters affect results','SRC-MAKERBOT-NYLON12CF-DATASHEET',names[3],[('tensile_strength',66,'MPa','supplier data; printed part parameter-dependent',1),('youngs_modulus',6,'GPa','supplier data; printed part parameter-dependent',1)])
 add('MAT-ROBOT-SEED-PPS-CF-FDM','UltiMaker PPS CF','FDM 短切碳纤维增强 PPS','PPS-CF','Factor 4 printer; HT 0.6 mm CC print core; 100% infill; 0.2 mm layers; conditioned at room temperature','SRC-ULTIMAKER-PPSCF-TDS-V1.00',names[4],[('density',1.28,'g/cm³','filament density',1),('youngs_modulus',4.376,'GPa','XY; ISO 527; printed; room temperature',2),('tensile_strength',47.3,'MPa','XY; ISO 527; printed; room temperature',2),('yield_strength',47.5,'MPa','XY; ISO 527; printed; room temperature',2),('elongation',2,'%', 'XY; ISO 527; printed; room temperature',2),('flexural_modulus',5.106,'GPa','XY; ISO 178; printed; room temperature',2),('flexural_strength',87,'MPa','XY; ISO 178; printed; room temperature',2),('heat_deflection_temperature',503.15,'K','0.45 MPa; ISO 75; annealed',3),('glass_transition_temperature',375.15,'K','DSC; filament',3),('z_axis_youngs_modulus',2.392,'GPa','Z axis; ISO 527; printed; room temperature',2),('z_axis_tensile_strength',20.1,'MPa','Z axis; ISO 527; printed; room temperature',2)])
 add('MAT-ROBOT-SEED-C11000','Kormax C11000 Copper','高导电电解铜','C11000','manufacturer product data; temper/product form not separately reported','SRC-KORMAX-C110-COPPER-2022',names[5],[('ultimate_tensile_strength',255,'MPa','manufacturer minimum; product form not separately reported',1),('hardness_rockwell_b',77,'HRB','manufacturer minimum; product form not separately reported; retained separately because HRB is not directly comparable with HRC/HV',1)])
 add('MAT-ROBOT-SEED-CF-PEKK-FDM','9T Labs CF/PEKK（AS4，60% 体积分数）','连续碳纤维/PEKK 复材','CF-PEKK','printed and consolidated coupon; AS4 fibre; 60% fibre volume fraction','SRC-9TLABS-CF-PEKK-2021-03',names[6],[('density',1.58,'g/cm³','printed and consolidated; AS4; fibre volume fraction 60%',1),('longitudinal_tensile_modulus',137,'GPa','0 degree; ISO 527; printed and consolidated',1),('longitudinal_tensile_strength',2350,'MPa','0 degree; ISO 527; printed and consolidated',1),('flexural_modulus',118,'GPa','0 degree; ISO 14125; printed and consolidated',1),('flexural_strength',1655,'MPa','0 degree; ISO 14125; printed and consolidated',1),('in_plane_shear_modulus',5.2,'GPa','ISO 14129; printed and consolidated',1),('shear_strength',145,'MPa','ISO 14129; printed and consolidated',1),('glass_transition_temperature',432.15,'K','DSC; material system',1)])
 add('MAT-ROBOT-SEED-IM7-8552','Hexcel IM7/8552（60% 纤维体积分数）','连续碳纤维/8552 环氧复材','IM7/8552','0° laminate; 60% fibre volume; room temperature; dry; specific layup per Hexcel datasheet','SRC-HEXCEL-IM7-8552-2023',names[7],[('longitudinal_tensile_strength',2723,'MPa','0 degree; dry; room temperature; ASTM D3039; 60% fibre volume',1),('longitudinal_tensile_modulus',164,'GPa','0 degree; dry; room temperature; 60% fibre volume',1),('elongation',1.6,'%', '0 degree; dry; room temperature; 60% fibre volume',1),('flexural_strength',1862,'MPa','0 degree; dry; room temperature; ASTM D790; 60% fibre volume',1),('flexural_modulus',152,'GPa','0 degree; dry; room temperature; 60% fibre volume',1),('shear_strength',128,'MPa','short beam shear; room temperature; ASTM D2344; 60% fibre volume',1),('compressive_strength',1689,'MPa','0 degree; room temperature; ASTM modified D695; 60% fibre volume',1),('density',1.56,'g/cm³','nominal cured laminate density; 60% fibre volume',1)])
 add('MAT-ROBOT-SEED-7075-T6','InstaVoxel 7075-T6 铝合金','高强铝合金','7075-T6','supplier datasheet; product form not separately reported; T6 solution heat-treated and artificially aged','SRC-INSTAVOXEL-7075T6-2024',names[8],[('density',2.81,'g/cm³','supplier datasheet; product form not separately reported',1),('ultimate_tensile_strength',572,'MPa','supplier datasheet; product form not separately reported',1),('yield_strength',503,'MPa','supplier datasheet; product form not separately reported',1),('hardness_rockwell_b',87,'HRB','supplier datasheet; product form not separately reported; retained separately because HRB is not directly comparable with HRC/HV',1),('elongation',9,'%', 'supplier datasheet; product form not separately reported',1),('thermal_conductivity',130,'W/(m·K)','supplier datasheet; product form not separately reported',1),('youngs_modulus',71.7,'GPa','supplier datasheet; product form not separately reported',1)])
 add('MAT-ROBOT-SEED-T700-EPOXY','Torayca T700S/环氧复材（60% 纤维体积分数）','连续碳纤维/环氧复材','T700/epoxy','normalized to 60% fibre volume; cured with epoxy at 130 °C; laminate layup not separately reported','SRC-TORAY-T700S-WEB-2026-08-25','', [('longitudinal_tensile_strength',2860,'MPa','normalized to 60% fibre volume; cured with epoxy at 130 °C; ASTM D3039', 'https://www.toraycma.com/wp-content/uploads/T700S-Data-Sheet-4.22.2025.pdf'),('longitudinal_tensile_modulus',134,'GPa','normalized to 60% fibre volume; cured with epoxy at 130 °C; ASTM D3039','https://www.toraycma.com/wp-content/uploads/T700S-Data-Sheet-4.22.2025.pdf'),('elongation',2.02,'%', 'normalized to 60% fibre volume; cured with epoxy at 130 °C; ASTM D3039','https://www.toraycma.com/wp-content/uploads/T700S-Data-Sheet-4.22.2025.pdf'),('compressive_strength',1450,'MPa','normalized to 60% fibre volume; cured with epoxy at 130 °C; SACMA SRM1R-94','https://www.toraycma.com/wp-content/uploads/T700S-Data-Sheet-4.22.2025.pdf'),('flexural_strength',1690,'MPa','normalized to 60% fibre volume; cured with epoxy at 130 °C; ASTM D790','https://www.toraycma.com/wp-content/uploads/T700S-Data-Sheet-4.22.2025.pdf'),('flexural_modulus',120,'GPa','normalized to 60% fibre volume; cured with epoxy at 130 °C; ASTM D790','https://www.toraycma.com/wp-content/uploads/T700S-Data-Sheet-4.22.2025.pdf'),('shear_strength',86.9,'MPa','interlaminar shear; normalized to 60% fibre volume; cured with epoxy at 130 °C','https://www.toraycma.com/wp-content/uploads/T700S-Data-Sheet-4.22.2025.pdf')])
 add('MAT-ROBOT-SEED-ALS10MG','EOS Aluminium AlSi10Mg','金属增材铝合金','AlSi10Mg','EOS aluminium additive-manufacturing part; process/heat treatment not separately selected','SRC-EOS-ALSI10MG-WEB-2026-08-25','', [('ultimate_tensile_strength',460,'MPa','EOS typical part properties; process/heat treatment not separately selected','https://www.eos.info/metal-solutions/metal-materials/aluminium'),('yield_strength',245,'MPa','EOS typical part properties; process/heat treatment not separately selected','https://www.eos.info/metal-solutions/metal-materials/aluminium'),('elongation',5,'%', 'EOS typical part properties; process/heat treatment not separately selected','https://www.eos.info/metal-solutions/metal-materials/aluminium')])
 add('MAT-ROBOT-SEED-PEKK-FDM','AON3D Readyprint Amorphous PEKK','FDM 高性能 PEKK 工程塑料','PEKK','AON3D printed specimen; XY or ZX direction as stated; production conditions affect values','SRC-AON3D-READyPRINT-PEKK-A-2023',names[9],[('density',1.261,'g/cm³','filament; ISO 1183-1',2),('thermal_conductivity',0.21,'W/(m·K)','XY printed specimen; ASTM E1530-11',2),('tensile_strength',92.1,'MPa','XY printed specimen; ISO 527-2/5A/50',3),('z_axis_tensile_strength',76.9,'MPa','ZX printed specimen; ISO 527-2/5A/50',3),('youngs_modulus',2.972,'GPa','XY printed specimen; ISO 527-2/5A/50',3),('z_axis_youngs_modulus',2.7,'GPa','ZX printed specimen; ISO 527-2/5A/50',3),('thermal_expansion_coefficient',53,'ppm/K','XY; -30 to 100 °C; ISO 11359-2/ASTM E228',2)])
 add('MAT-ROBOT-SEED-2024-T3','Gabrian 2024-T3 铝合金','航空铝合金','2024-T3','supplier datasheet; T3 temper; product form not separately reported','SRC-GABRIAN-2024T3-2018',names[10],[('density',2.78,'g/cm³','2024-T3; supplier datasheet',1),('ultimate_tensile_strength',483,'MPa','2024-T3; supplier datasheet',1),('yield_strength',345,'MPa','2024-T3; supplier datasheet',1),('youngs_modulus',73.1,'GPa','2024-T3; supplier datasheet',1),('thermal_conductivity',121,'W/(m·K)','2024-T3; supplier datasheet',1),('thermal_expansion_coefficient',23.2,'ppm/K','2024-T3; 20 to 100 °C',1)])
 add('MAT-ROBOT-SEED-20MNCR5','Ovako 20MnCr5 渗碳钢','齿轮渗碳钢','20MnCr5','Ovako grade 20MnCr5; typical ambient physical properties; heat-treatment state must be selected for strength','SRC-OVAKO-20MNCR5-2025',names[11],[('density',7800,'kg/m³','Ovako typical value',4),('thermal_conductivity',40,'W/(m·K)','ambient; datasheet range 40–45 W/(m·K); lower endpoint retained',4),('youngs_modulus',210,'GPa','Ovako typical value',4),('thermal_expansion_coefficient',12,'ppm/K','average 20–300 °C',4)])
 add('MAT-ROBOT-SEED-AZ91','Exclusive Magnesium AZ91C-T4','铸造镁合金','AZ91','AZ91C; T4; sand casting; room-temperature supplier data','SRC-EXCLUSIVE-MAGNESIUM-AZ91-2026',names[12],[('density',1.79,'g/cm³','AZ91C T4; sand casting',1),('ultimate_tensile_strength',234,'MPa','AZ91C T4; sand casting',1),('thermal_conductivity',72,'W/(m·K)','AZ91C T4; sand casting',1),('yield_strength',76,'MPa','AZ91C T4; sand casting; 0.2% offset',1),('youngs_modulus',44.8,'GPa','AZ91C T4; sand casting',1),('thermal_expansion_coefficient',26,'ppm/K','AZ91C T4; sand casting',1),('elongation',7,'%', 'AZ91C T4; sand casting; 50 mm',1)])
 a.output.mkdir(parents=True)
 for n,fs,d in [('materials.csv',tuple(ms[0]),ms),('property_points.csv',F,pts),('material_aliases.csv',('material_id','alias','alias_type','source'),als),('curve_data.csv',(),[]),('composition_long.csv',(),[])]:
  with(a.output/n).open('w',encoding='utf-8',newline='') as h:w=csv.DictWriter(h,fieldnames=fs);w.writeheader();w.writerows(d)
 (a.output/'import_manifest.json').write_text(json.dumps({'sources':{n:hashlib.sha256((a.source_dir/n).read_bytes()).hexdigest() for n in names},'web_sources':{'SRC-TORAY-T700S-WEB-2026-08-25':'https://www.toraycma.com/wp-content/uploads/T700S-Data-Sheet-4.22.2025.pdf','SRC-EOS-ALSI10MG-WEB-2026-08-25':'https://www.eos.info/metal-solutions/metal-materials/aluminium'},'counts':{'materials':len(ms),'property_points':len(pts)},'review':'2026-08-25'},indent=2)+'\n')
if __name__=='__main__':main()
