"""Starter property profiles for engineering 3D-printing filament selection."""

from __future__ import annotations

from typing import Any, Dict, List


JsonDict = Dict[str, Any]


STARTER_FILAMENT_PROFILES: List[JsonDict] = [
    {
        "name": "ABS-GF",
        "display_name": "玻纤增强 ABS",
        "family": "ABS",
        "tags": ["glass_fiber", "stiff", "heat_resistant", "enclosure_required"],
        "properties": {
            "impact_xy_kj_m2": 14.5,
            "flexural_strength_mpa": 68.0,
            "flexural_modulus_mpa": 2860.0,
            "z_impact_kj_m2": 5.3,
            "hdt_045_mpa_c": 99.0,
            "water_absorption_pct": 0.53,
        },
        "process": {
            "drying": "推荐干燥；鼓风烘箱 80 C, 8 h",
            "nozzle": "0.6 mm 推荐；硬化钢喷嘴",
            "bed": "PEI 90-100 C",
            "nozzle_temp": "240-280 C",
            "speed": "< 180 mm/s",
            "enclosure": "必需",
        },
        "advantages": ["刚度高", "耐热性较好", "尺寸稳定性优于未增强 ABS"],
        "limitations": ["层间冲击弱于 XY 方向", "导热能力不是专门优化项"],
        "evidence": "starter_profile: Bambu filament table fields captured from upstream/RAG",
    },
    {
        "name": "ASA",
        "display_name": "ASA",
        "family": "ASA",
        "tags": ["weather_resistant", "heat_resistant", "enclosure_required"],
        "properties": {
            "impact_xy_kj_m2": 41.0,
            "flexural_strength_mpa": 65.0,
            "flexural_modulus_mpa": 1920.0,
            "z_impact_kj_m2": 4.9,
            "hdt_045_mpa_c": 100.0,
            "water_absorption_pct": 0.45,
        },
        "process": {
            "drying": "推荐干燥；鼓风烘箱 80 C, 8 h",
            "nozzle": "全尺寸/材质",
            "bed": "PEI 90-100 C",
            "nozzle_temp": "240-280 C",
            "speed": "< 300 mm/s",
            "enclosure": "必需",
        },
        "advantages": ["冲击韧性好", "耐热性较好", "吸水率较低"],
        "limitations": ["刚度一般", "层间粘接代理指标偏低"],
        "evidence": "starter_profile: Bambu filament table fields captured from upstream/RAG",
    },
    {
        "name": "PETG HF",
        "display_name": "高速 PETG",
        "family": "PETG",
        "tags": ["easy_print", "moderate_toughness", "low_warp"],
        "properties": {
            "impact_xy_kj_m2": 31.5,
            "flexural_strength_mpa": 64.0,
            "flexural_modulus_mpa": 2050.0,
            "z_impact_kj_m2": 10.6,
            "hdt_045_mpa_c": 69.0,
            "water_absorption_pct": 0.40,
        },
        "process": {
            "drying": "需要干燥；鼓风烘箱 65 C, 8 h",
            "nozzle": "全尺寸/材质",
            "bed": "PEI 60-80 C",
            "nozzle_temp": "230-260 C",
            "speed": "< 300 mm/s",
            "enclosure": "可选",
        },
        "advantages": ["层间粘接代理指标较好", "吸水率低", "打印窗口友好"],
        "limitations": ["耐热性不足", "刚度不适合高承载关节"],
        "evidence": "starter_profile: Bambu filament table fields captured from upstream/RAG",
    },
    {
        "name": "ABS",
        "display_name": "ABS",
        "family": "ABS",
        "tags": ["tough", "heat_resistant", "enclosure_required"],
        "properties": {
            "impact_xy_kj_m2": 39.3,
            "flexural_strength_mpa": 62.0,
            "flexural_modulus_mpa": 1880.0,
            "z_impact_kj_m2": 7.4,
            "hdt_045_mpa_c": 87.0,
            "water_absorption_pct": 0.65,
        },
        "process": {
            "drying": "推荐干燥；鼓风烘箱 80 C, 8 h",
            "nozzle": "全尺寸/材质",
            "bed": "PEI 90-100 C",
            "nozzle_temp": "240-280 C",
            "speed": "< 300 mm/s",
            "enclosure": "必需",
        },
        "advantages": ["冲击韧性好", "耐热性中等"],
        "limitations": ["吸水率较高", "刚度一般", "打印需封箱"],
        "evidence": "starter_profile: Bambu filament table fields captured from upstream/RAG",
    },
    {
        "name": "PLA",
        "display_name": "PLA",
        "family": "PLA",
        "tags": ["easy_print", "stiff"],
        "properties": {
            "impact_xy_kj_m2": 26.6,
            "flexural_strength_mpa": 76.0,
            "flexural_modulus_mpa": 2750.0,
            "z_impact_kj_m2": 13.8,
            "hdt_045_mpa_c": 57.0,
            "water_absorption_pct": 0.43,
        },
        "process": {
            "drying": "推荐干燥；鼓风烘箱 55 C, 8 h",
            "nozzle": "全尺寸/材质",
            "bed": "35-65 C",
            "nozzle_temp": "190-230 C",
            "speed": "< 300 mm/s",
            "enclosure": "可选",
        },
        "advantages": ["刚度较高", "层间粘接代理指标好", "易打印"],
        "limitations": ["耐热性不足", "不适合作为高温关节结构件"],
        "evidence": "starter_profile: Bambu filament table fields captured from upstream/RAG",
    },
    {
        "name": "PA6-CF",
        "display_name": "碳纤维增强 PA6",
        "family": "PA",
        "tags": ["carbon_fiber", "stiff", "engineering", "drying_required", "thermal_path_candidate"],
        "properties": {
            "thermal_conductivity_w_mk": None,
            "flexural_modulus_mpa": None,
            "hdt_045_mpa_c": None,
            "water_absorption_pct": None,
        },
        "process": {
            "drying": "必须充分干燥；按供应商 TDS 设置",
            "nozzle": "硬化钢喷嘴",
            "bed": "高温热床；建议封箱",
            "nozzle_temp": "按供应商 TDS 设置",
            "speed": "中低速优先",
            "enclosure": "推荐",
        },
        "advantages": ["高刚度潜力", "适合承载结构", "碳纤维可提供面内导热通道"],
        "limitations": ["吸湿敏感", "Z 向层间性能和导热需实测", "参数依赖具体牌号"],
        "evidence": "starter_profile: generic engineering family; replace with RAG/TDS values when upstream supplies properties",
    },
    {
        "name": "PA12-CF",
        "display_name": "碳纤维增强 PA12",
        "family": "PA",
        "tags": ["carbon_fiber", "stiff", "engineering", "lower_moisture_than_pa6", "thermal_path_candidate"],
        "properties": {
            "thermal_conductivity_w_mk": None,
            "flexural_modulus_mpa": None,
            "hdt_045_mpa_c": None,
            "water_absorption_pct": None,
        },
        "process": {
            "drying": "必须干燥；按供应商 TDS 设置",
            "nozzle": "硬化钢喷嘴",
            "bed": "高温热床；建议封箱",
            "nozzle_temp": "按供应商 TDS 设置",
            "speed": "中低速优先",
            "enclosure": "推荐",
        },
        "advantages": ["尺寸稳定性通常优于 PA6", "刚度和轻量化潜力好"],
        "limitations": ["导热和层间强度需按具体牌号核验", "高散热需求可能仍不足"],
        "evidence": "starter_profile: generic engineering family; replace with RAG/TDS values when upstream supplies properties",
    },
    {
        "name": "PC-CF",
        "display_name": "碳纤维增强 PC",
        "family": "PC",
        "tags": ["carbon_fiber", "stiff", "heat_resistant", "engineering", "enclosure_required"],
        "properties": {
            "thermal_conductivity_w_mk": None,
            "flexural_modulus_mpa": None,
            "hdt_045_mpa_c": None,
            "water_absorption_pct": None,
        },
        "process": {
            "drying": "必须干燥；按供应商 TDS 设置",
            "nozzle": "硬化钢喷嘴",
            "bed": "高温热床；封箱",
            "nozzle_temp": "按供应商 TDS 设置",
            "speed": "中低速优先",
            "enclosure": "必需",
        },
        "advantages": ["耐热和刚度潜力较好", "适合高温结构验证"],
        "limitations": ["打印窗口更苛刻", "层间和翘曲风险需控制"],
        "evidence": "starter_profile: generic engineering family; replace with RAG/TDS values when upstream supplies properties",
    },
]


def starter_profiles() -> List[JsonDict]:
    """Return independent profile copies for scoring."""
    return [dict(item, properties=dict(item.get("properties", {})), process=dict(item.get("process", {}))) for item in STARTER_FILAMENT_PROFILES]
